---
version: '3.8'

services:
  tyk-plugin-compiler:
    image: tykio/tyk-plugin-compiler:${TYK_VERSION}
    platform: linux/amd64
    volumes:
      - ./bundles/simple:/plugin-source
    networks:
      - tyk

  tyk-gateway:
    image: tykio/tyk-gateway:${TYK_VERSION}
    platform: linux/amd64
    volumes:
      - ./bundles/simple:/plugin-source
    networks:
      - tyk

  mongodb:
    image: mongo:6.0
    restart: always
    environment:
      - AUTH=no
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - tyk

  mserv:
    build: .
    restart: always
    volumes:
      - ./mserv_example.conf:/etc/mserv/mserv.json
    depends_on:
      - mongodb
    ports:
      - "8989:8989"
    networks:
      - tyk

volumes:
  mongo-data:

networks:
  tyk:
