// Code generated by go-swagger; DO NOT EDIT.

package invocation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/TykTechnologies/mserv/mservclient/models"
)

// NewInvokeParams creates a new InvokeParams object
// with the default values initialized.
func NewInvokeParams() *InvokeParams {
	var ()
	return &InvokeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewInvokeParamsWithTimeout creates a new InvokeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewInvokeParamsWithTimeout(timeout time.Duration) *InvokeParams {
	var ()
	return &InvokeParams{

		timeout: timeout,
	}
}

// NewInvokeParamsWithContext creates a new InvokeParams object
// with the default values initialized, and the ability to set a context for a request
func NewInvokeParamsWithContext(ctx context.Context) *InvokeParams {
	var ()
	return &InvokeParams{

		Context: ctx,
	}
}

// NewInvokeParamsWithHTTPClient creates a new InvokeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewInvokeParamsWithHTTPClient(client *http.Client) *InvokeParams {
	var ()
	return &InvokeParams{
		HTTPClient: client,
	}
}

/*InvokeParams contains all the parameters to send to the API endpoint
for the invoke operation typically these are written to a http.Request
*/
type InvokeParams struct {

	/*Body*/
	Body *models.Object
	/*Name*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the invoke params
func (o *InvokeParams) WithTimeout(timeout time.Duration) *InvokeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the invoke params
func (o *InvokeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the invoke params
func (o *InvokeParams) WithContext(ctx context.Context) *InvokeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the invoke params
func (o *InvokeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the invoke params
func (o *InvokeParams) WithHTTPClient(client *http.Client) *InvokeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the invoke params
func (o *InvokeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the invoke params
func (o *InvokeParams) WithBody(body *models.Object) *InvokeParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the invoke params
func (o *InvokeParams) SetBody(body *models.Object) {
	o.Body = body
}

// WithName adds the name to the invoke params
func (o *InvokeParams) WithName(name string) *InvokeParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the invoke params
func (o *InvokeParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *InvokeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
