// Code generated by go-swagger; DO NOT EDIT.

package invocation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/TykTechnologies/mserv/mservclient/models"
)

// InvokeReader is a Reader for the Invoke structure.
type InvokeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *InvokeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewInvokeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewInvokeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /execute/{name}] invoke", response, response.Code())
	}
}

// NewInvokeOK creates a InvokeOK with default headers values
func NewInvokeOK() *InvokeOK {
	return &InvokeOK{}
}

/*
InvokeOK describes a response with status code 200, with default header values.

Middleware invocation response
*/
type InvokeOK struct {
	Payload *InvokeOKBody
}

// IsSuccess returns true when this invoke o k response has a 2xx status code
func (o *InvokeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this invoke o k response has a 3xx status code
func (o *InvokeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this invoke o k response has a 4xx status code
func (o *InvokeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this invoke o k response has a 5xx status code
func (o *InvokeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this invoke o k response a status code equal to that given
func (o *InvokeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the invoke o k response
func (o *InvokeOK) Code() int {
	return 200
}

func (o *InvokeOK) Error() string {
	return fmt.Sprintf("[POST /execute/{name}][%d] invokeOK  %+v", 200, o.Payload)
}

func (o *InvokeOK) String() string {
	return fmt.Sprintf("[POST /execute/{name}][%d] invokeOK  %+v", 200, o.Payload)
}

func (o *InvokeOK) GetPayload() *InvokeOKBody {
	return o.Payload
}

func (o *InvokeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(InvokeOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewInvokeInternalServerError creates a InvokeInternalServerError with default headers values
func NewInvokeInternalServerError() *InvokeInternalServerError {
	return &InvokeInternalServerError{}
}

/*
InvokeInternalServerError describes a response with status code 500, with default header values.

Generic error specified by `Status` and `Error` fields
*/
type InvokeInternalServerError struct {
	Payload *models.Payload
}

// IsSuccess returns true when this invoke internal server error response has a 2xx status code
func (o *InvokeInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this invoke internal server error response has a 3xx status code
func (o *InvokeInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this invoke internal server error response has a 4xx status code
func (o *InvokeInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this invoke internal server error response has a 5xx status code
func (o *InvokeInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this invoke internal server error response a status code equal to that given
func (o *InvokeInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the invoke internal server error response
func (o *InvokeInternalServerError) Code() int {
	return 500
}

func (o *InvokeInternalServerError) Error() string {
	return fmt.Sprintf("[POST /execute/{name}][%d] invokeInternalServerError  %+v", 500, o.Payload)
}

func (o *InvokeInternalServerError) String() string {
	return fmt.Sprintf("[POST /execute/{name}][%d] invokeInternalServerError  %+v", 500, o.Payload)
}

func (o *InvokeInternalServerError) GetPayload() *models.Payload {
	return o.Payload
}

func (o *InvokeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Payload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
InvokeOKBody invoke o k body
swagger:model InvokeOKBody
*/
type InvokeOKBody struct {

	// error
	Error string `json:"Error,omitempty"`

	// payload
	Payload *models.Object `json:"Payload,omitempty"`

	// status
	Status string `json:"Status,omitempty"`
}

// Validate validates this invoke o k body
func (o *InvokeOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validatePayload(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *InvokeOKBody) validatePayload(formats strfmt.Registry) error {
	if swag.IsZero(o.Payload) { // not required
		return nil
	}

	if o.Payload != nil {
		if err := o.Payload.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("invokeOK" + "." + "Payload")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("invokeOK" + "." + "Payload")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this invoke o k body based on the context it is used
func (o *InvokeOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidatePayload(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *InvokeOKBody) contextValidatePayload(ctx context.Context, formats strfmt.Registry) error {

	if o.Payload != nil {

		if swag.IsZero(o.Payload) { // not required
			return nil
		}

		if err := o.Payload.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("invokeOK" + "." + "Payload")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("invokeOK" + "." + "Payload")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *InvokeOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *InvokeOKBody) UnmarshalBinary(b []byte) error {
	var res InvokeOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
