// Code generated by go-swagger; DO NOT EDIT.

package mw

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/TykTechnologies/mserv/mservclient/models"
)

// MwDeleteReader is a Reader for the MwDelete structure.
type MwDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MwDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMwDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewMwDeleteInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewMwDeleteOK creates a MwDeleteOK with default headers values
func NewMwDeleteOK() *MwDeleteOK {
	return &MwDeleteOK{}
}

/*MwDeleteOK handles this case with default header values.

Response that only includes the ID of the middleware as `BundleID` in the `Payload`
*/
type MwDeleteOK struct {
	Payload *MwDeleteOKBody
}

func (o *MwDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /api/mw/{id}][%d] mwDeleteOK  %+v", 200, o.Payload)
}

func (o *MwDeleteOK) GetPayload() *MwDeleteOKBody {
	return o.Payload
}

func (o *MwDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(MwDeleteOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMwDeleteInternalServerError creates a MwDeleteInternalServerError with default headers values
func NewMwDeleteInternalServerError() *MwDeleteInternalServerError {
	return &MwDeleteInternalServerError{}
}

/*MwDeleteInternalServerError handles this case with default header values.

Generic error specified by `Status` and `Error` fields
*/
type MwDeleteInternalServerError struct {
	Payload *models.Payload
}

func (o *MwDeleteInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /api/mw/{id}][%d] mwDeleteInternalServerError  %+v", 500, o.Payload)
}

func (o *MwDeleteInternalServerError) GetPayload() *models.Payload {
	return o.Payload
}

func (o *MwDeleteInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Payload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*MwDeleteOKBody mw delete o k body
swagger:model MwDeleteOKBody
*/
type MwDeleteOKBody struct {

	// error
	Error string `json:"Error,omitempty"`

	// payload
	Payload *MwDeleteOKBodyPayload `json:"Payload,omitempty"`

	// status
	Status string `json:"Status,omitempty"`
}

// Validate validates this mw delete o k body
func (o *MwDeleteOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validatePayload(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *MwDeleteOKBody) validatePayload(formats strfmt.Registry) error {

	if swag.IsZero(o.Payload) { // not required
		return nil
	}

	if o.Payload != nil {
		if err := o.Payload.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("mwDeleteOK" + "." + "Payload")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *MwDeleteOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *MwDeleteOKBody) UnmarshalBinary(b []byte) error {
	var res MwDeleteOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*MwDeleteOKBodyPayload mw delete o k body payload
swagger:model MwDeleteOKBodyPayload
*/
type MwDeleteOKBodyPayload struct {

	// bundle ID
	BundleID string `json:"BundleID,omitempty"`
}

// Validate validates this mw delete o k body payload
func (o *MwDeleteOKBodyPayload) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *MwDeleteOKBodyPayload) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *MwDeleteOKBodyPayload) UnmarshalBinary(b []byte) error {
	var res MwDeleteOKBodyPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
