// Code generated by go-swagger; DO NOT EDIT.

package mw

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewMwFetchBundleParams creates a new MwFetchBundleParams object
// with the default values initialized.
func NewMwFetchBundleParams() *MwFetchBundleParams {
	var ()
	return &MwFetchBundleParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMwFetchBundleParamsWithTimeout creates a new MwFetchBundleParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMwFetchBundleParamsWithTimeout(timeout time.Duration) *MwFetchBundleParams {
	var ()
	return &MwFetchBundleParams{

		timeout: timeout,
	}
}

// NewMwFetchBundleParamsWithContext creates a new MwFetchBundleParams object
// with the default values initialized, and the ability to set a context for a request
func NewMwFetchBundleParamsWithContext(ctx context.Context) *MwFetchBundleParams {
	var ()
	return &MwFetchBundleParams{

		Context: ctx,
	}
}

// NewMwFetchBundleParamsWithHTTPClient creates a new MwFetchBundleParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMwFetchBundleParamsWithHTTPClient(client *http.Client) *MwFetchBundleParams {
	var ()
	return &MwFetchBundleParams{
		HTTPClient: client,
	}
}

/*MwFetchBundleParams contains all the parameters to send to the API endpoint
for the mw fetch bundle operation typically these are written to a http.Request
*/
type MwFetchBundleParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the mw fetch bundle params
func (o *MwFetchBundleParams) WithTimeout(timeout time.Duration) *MwFetchBundleParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the mw fetch bundle params
func (o *MwFetchBundleParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the mw fetch bundle params
func (o *MwFetchBundleParams) WithContext(ctx context.Context) *MwFetchBundleParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the mw fetch bundle params
func (o *MwFetchBundleParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the mw fetch bundle params
func (o *MwFetchBundleParams) WithHTTPClient(client *http.Client) *MwFetchBundleParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the mw fetch bundle params
func (o *MwFetchBundleParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the mw fetch bundle params
func (o *MwFetchBundleParams) WithID(id string) *MwFetchBundleParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the mw fetch bundle params
func (o *MwFetchBundleParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *MwFetchBundleParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
