// Code generated by go-swagger; DO NOT EDIT.

package mw

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewMwFetchParams creates a new MwFetchParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMwFetchParams() *MwFetchParams {
	return &MwFetchParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMwFetchParamsWithTimeout creates a new MwFetchParams object
// with the ability to set a timeout on a request.
func NewMwFetchParamsWithTimeout(timeout time.Duration) *MwFetchParams {
	return &MwFetchParams{
		timeout: timeout,
	}
}

// NewMwFetchParamsWithContext creates a new MwFetchParams object
// with the ability to set a context for a request.
func NewMwFetchParamsWithContext(ctx context.Context) *MwFetchParams {
	return &MwFetchParams{
		Context: ctx,
	}
}

// NewMwFetchParamsWithHTTPClient creates a new MwFetchParams object
// with the ability to set a custom HTTPClient for a request.
func NewMwFetchParamsWithHTTPClient(client *http.Client) *MwFetchParams {
	return &MwFetchParams{
		HTTPClient: client,
	}
}

/*
MwFetchParams contains all the parameters to send to the API endpoint

	for the mw fetch operation.

	Typically these are written to a http.Request.
*/
type MwFetchParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the mw fetch params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MwFetchParams) WithDefaults() *MwFetchParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the mw fetch params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MwFetchParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the mw fetch params
func (o *MwFetchParams) WithTimeout(timeout time.Duration) *MwFetchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the mw fetch params
func (o *MwFetchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the mw fetch params
func (o *MwFetchParams) WithContext(ctx context.Context) *MwFetchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the mw fetch params
func (o *MwFetchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the mw fetch params
func (o *MwFetchParams) WithHTTPClient(client *http.Client) *MwFetchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the mw fetch params
func (o *MwFetchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the mw fetch params
func (o *MwFetchParams) WithID(id string) *MwFetchParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the mw fetch params
func (o *MwFetchParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *MwFetchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
