// Code generated by go-swagger; DO NOT EDIT.

package mw

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/TykTechnologies/mserv/mservclient/models"
)

// MwFetchReader is a Reader for the MwFetch structure.
type MwFetchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MwFetchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMwFetchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewMwFetchInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/mw/{id}] mwFetch", response, response.Code())
	}
}

// NewMwFetchOK creates a MwFetchOK with default headers values
func NewMwFetchOK() *MwFetchOK {
	return &MwFetchOK{}
}

/*
MwFetchOK describes a response with status code 200, with default header values.

Full middleware response in the `Payload`
*/
type MwFetchOK struct {
	Payload *MwFetchOKBody
}

// IsSuccess returns true when this mw fetch o k response has a 2xx status code
func (o *MwFetchOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this mw fetch o k response has a 3xx status code
func (o *MwFetchOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this mw fetch o k response has a 4xx status code
func (o *MwFetchOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this mw fetch o k response has a 5xx status code
func (o *MwFetchOK) IsServerError() bool {
	return false
}

// IsCode returns true when this mw fetch o k response a status code equal to that given
func (o *MwFetchOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the mw fetch o k response
func (o *MwFetchOK) Code() int {
	return 200
}

func (o *MwFetchOK) Error() string {
	return fmt.Sprintf("[GET /api/mw/{id}][%d] mwFetchOK  %+v", 200, o.Payload)
}

func (o *MwFetchOK) String() string {
	return fmt.Sprintf("[GET /api/mw/{id}][%d] mwFetchOK  %+v", 200, o.Payload)
}

func (o *MwFetchOK) GetPayload() *MwFetchOKBody {
	return o.Payload
}

func (o *MwFetchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(MwFetchOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMwFetchInternalServerError creates a MwFetchInternalServerError with default headers values
func NewMwFetchInternalServerError() *MwFetchInternalServerError {
	return &MwFetchInternalServerError{}
}

/*
MwFetchInternalServerError describes a response with status code 500, with default header values.

Generic error specified by `Status` and `Error` fields
*/
type MwFetchInternalServerError struct {
	Payload *models.Payload
}

// IsSuccess returns true when this mw fetch internal server error response has a 2xx status code
func (o *MwFetchInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this mw fetch internal server error response has a 3xx status code
func (o *MwFetchInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this mw fetch internal server error response has a 4xx status code
func (o *MwFetchInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this mw fetch internal server error response has a 5xx status code
func (o *MwFetchInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this mw fetch internal server error response a status code equal to that given
func (o *MwFetchInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the mw fetch internal server error response
func (o *MwFetchInternalServerError) Code() int {
	return 500
}

func (o *MwFetchInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/mw/{id}][%d] mwFetchInternalServerError  %+v", 500, o.Payload)
}

func (o *MwFetchInternalServerError) String() string {
	return fmt.Sprintf("[GET /api/mw/{id}][%d] mwFetchInternalServerError  %+v", 500, o.Payload)
}

func (o *MwFetchInternalServerError) GetPayload() *models.Payload {
	return o.Payload
}

func (o *MwFetchInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Payload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
MwFetchOKBody mw fetch o k body
swagger:model MwFetchOKBody
*/
type MwFetchOKBody struct {

	// error
	Error string `json:"Error,omitempty"`

	// payload
	Payload *models.MW `json:"Payload,omitempty"`

	// status
	Status string `json:"Status,omitempty"`
}

// Validate validates this mw fetch o k body
func (o *MwFetchOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validatePayload(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *MwFetchOKBody) validatePayload(formats strfmt.Registry) error {
	if swag.IsZero(o.Payload) { // not required
		return nil
	}

	if o.Payload != nil {
		if err := o.Payload.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("mwFetchOK" + "." + "Payload")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("mwFetchOK" + "." + "Payload")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this mw fetch o k body based on the context it is used
func (o *MwFetchOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidatePayload(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *MwFetchOKBody) contextValidatePayload(ctx context.Context, formats strfmt.Registry) error {

	if o.Payload != nil {

		if swag.IsZero(o.Payload) { // not required
			return nil
		}

		if err := o.Payload.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("mwFetchOK" + "." + "Payload")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("mwFetchOK" + "." + "Payload")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *MwFetchOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *MwFetchOKBody) UnmarshalBinary(b []byte) error {
	var res MwFetchOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
