// Code generated by go-swagger; DO NOT EDIT.

package mw

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/TykTechnologies/mserv/mservclient/models"
)

// MwFetchBundleReader is a Reader for the MwFetchBundle structure.
type MwFetchBundleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MwFetchBundleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMwFetchBundleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewMwFetchBundleInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /api/mw/bundle/{id}] mwFetchBundle", response, response.Code())
	}
}

// NewMwFetchBundleOK creates a MwFetchBundleOK with default headers values
func NewMwFetchBundleOK() *MwFetchBundleOK {
	return &MwFetchBundleOK{}
}

/*
MwFetchBundleOK describes a response with status code 200, with default header values.

Middleware bundle as a file
*/
type MwFetchBundleOK struct {
	Payload *models.File
}

// IsSuccess returns true when this mw fetch bundle o k response has a 2xx status code
func (o *MwFetchBundleOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this mw fetch bundle o k response has a 3xx status code
func (o *MwFetchBundleOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this mw fetch bundle o k response has a 4xx status code
func (o *MwFetchBundleOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this mw fetch bundle o k response has a 5xx status code
func (o *MwFetchBundleOK) IsServerError() bool {
	return false
}

// IsCode returns true when this mw fetch bundle o k response a status code equal to that given
func (o *MwFetchBundleOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the mw fetch bundle o k response
func (o *MwFetchBundleOK) Code() int {
	return 200
}

func (o *MwFetchBundleOK) Error() string {
	return fmt.Sprintf("[GET /api/mw/bundle/{id}][%d] mwFetchBundleOK  %+v", 200, o.Payload)
}

func (o *MwFetchBundleOK) String() string {
	return fmt.Sprintf("[GET /api/mw/bundle/{id}][%d] mwFetchBundleOK  %+v", 200, o.Payload)
}

func (o *MwFetchBundleOK) GetPayload() *models.File {
	return o.Payload
}

func (o *MwFetchBundleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.File)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMwFetchBundleInternalServerError creates a MwFetchBundleInternalServerError with default headers values
func NewMwFetchBundleInternalServerError() *MwFetchBundleInternalServerError {
	return &MwFetchBundleInternalServerError{}
}

/*
MwFetchBundleInternalServerError describes a response with status code 500, with default header values.

Generic error specified by `Status` and `Error` fields
*/
type MwFetchBundleInternalServerError struct {
	Payload *models.Payload
}

// IsSuccess returns true when this mw fetch bundle internal server error response has a 2xx status code
func (o *MwFetchBundleInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this mw fetch bundle internal server error response has a 3xx status code
func (o *MwFetchBundleInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this mw fetch bundle internal server error response has a 4xx status code
func (o *MwFetchBundleInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this mw fetch bundle internal server error response has a 5xx status code
func (o *MwFetchBundleInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this mw fetch bundle internal server error response a status code equal to that given
func (o *MwFetchBundleInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the mw fetch bundle internal server error response
func (o *MwFetchBundleInternalServerError) Code() int {
	return 500
}

func (o *MwFetchBundleInternalServerError) Error() string {
	return fmt.Sprintf("[GET /api/mw/bundle/{id}][%d] mwFetchBundleInternalServerError  %+v", 500, o.Payload)
}

func (o *MwFetchBundleInternalServerError) String() string {
	return fmt.Sprintf("[GET /api/mw/bundle/{id}][%d] mwFetchBundleInternalServerError  %+v", 500, o.Payload)
}

func (o *MwFetchBundleInternalServerError) GetPayload() *models.Payload {
	return o.Payload
}

func (o *MwFetchBundleInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Payload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
