// Code generated by go-swagger; DO NOT EDIT.

package mw

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewMwListAllParams creates a new MwListAllParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMwListAllParams() *MwListAllParams {
	return &MwListAllParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMwListAllParamsWithTimeout creates a new MwListAllParams object
// with the ability to set a timeout on a request.
func NewMwListAllParamsWithTimeout(timeout time.Duration) *MwListAllParams {
	return &MwListAllParams{
		timeout: timeout,
	}
}

// NewMwListAllParamsWithContext creates a new MwListAllParams object
// with the ability to set a context for a request.
func NewMwListAllParamsWithContext(ctx context.Context) *MwListAllParams {
	return &MwListAllParams{
		Context: ctx,
	}
}

// NewMwListAllParamsWithHTTPClient creates a new MwListAllParams object
// with the ability to set a custom HTTPClient for a request.
func NewMwListAllParamsWithHTTPClient(client *http.Client) *MwListAllParams {
	return &MwListAllParams{
		HTTPClient: client,
	}
}

/*
MwListAllParams contains all the parameters to send to the API endpoint

	for the mw list all operation.

	Typically these are written to a http.Request.
*/
type MwListAllParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the mw list all params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MwListAllParams) WithDefaults() *MwListAllParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the mw list all params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MwListAllParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the mw list all params
func (o *MwListAllParams) WithTimeout(timeout time.Duration) *MwListAllParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the mw list all params
func (o *MwListAllParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the mw list all params
func (o *MwListAllParams) WithContext(ctx context.Context) *MwListAllParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the mw list all params
func (o *MwListAllParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the mw list all params
func (o *MwListAllParams) WithHTTPClient(client *http.Client) *MwListAllParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the mw list all params
func (o *MwListAllParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *MwListAllParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
