// Code generated by go-swagger; DO NOT EDIT.

package mw

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewMwUpdateParams creates a new MwUpdateParams object
// with the default values initialized.
func NewMwUpdateParams() *MwUpdateParams {
	var ()
	return &MwUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewMwUpdateParamsWithTimeout creates a new MwUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewMwUpdateParamsWithTimeout(timeout time.Duration) *MwUpdateParams {
	var ()
	return &MwUpdateParams{

		timeout: timeout,
	}
}

// NewMwUpdateParamsWithContext creates a new MwUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewMwUpdateParamsWithContext(ctx context.Context) *MwUpdateParams {
	var ()
	return &MwUpdateParams{

		Context: ctx,
	}
}

// NewMwUpdateParamsWithHTTPClient creates a new MwUpdateParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewMwUpdateParamsWithHTTPClient(client *http.Client) *MwUpdateParams {
	var ()
	return &MwUpdateParams{
		HTTPClient: client,
	}
}

/*MwUpdateParams contains all the parameters to send to the API endpoint
for the mw update operation typically these are written to a http.Request
*/
type MwUpdateParams struct {

	/*ID*/
	ID string
	/*Uploadfile*/
	UploadFile runtime.NamedReadCloser

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the mw update params
func (o *MwUpdateParams) WithTimeout(timeout time.Duration) *MwUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the mw update params
func (o *MwUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the mw update params
func (o *MwUpdateParams) WithContext(ctx context.Context) *MwUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the mw update params
func (o *MwUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the mw update params
func (o *MwUpdateParams) WithHTTPClient(client *http.Client) *MwUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the mw update params
func (o *MwUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the mw update params
func (o *MwUpdateParams) WithID(id string) *MwUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the mw update params
func (o *MwUpdateParams) SetID(id string) {
	o.ID = id
}

// WithUploadFile adds the uploadfile to the mw update params
func (o *MwUpdateParams) WithUploadFile(uploadfile runtime.NamedReadCloser) *MwUpdateParams {
	o.SetUploadFile(uploadfile)
	return o
}

// SetUploadFile adds the uploadfile to the mw update params
func (o *MwUpdateParams) SetUploadFile(uploadfile runtime.NamedReadCloser) {
	o.UploadFile = uploadfile
}

// WriteToRequest writes these params to a swagger request
func (o *MwUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// form file param uploadfile
	if err := r.SetFileParam("uploadfile", o.UploadFile); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
