// Code generated by go-swagger; DO NOT EDIT.

package mw

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/TykTechnologies/mserv/mservclient/models"
)

// MwUpdateReader is a Reader for the MwUpdate structure.
type MwUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MwUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMwUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 500:
		result := NewMwUpdateInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewMwUpdateOK creates a MwUpdateOK with default headers values
func NewMwUpdateOK() *MwUpdateOK {
	return &MwUpdateOK{}
}

/*MwUpdateOK handles this case with default header values.

Response that only includes the ID of the middleware as `BundleID` in the `Payload`
*/
type MwUpdateOK struct {
	Payload *MwUpdateOKBody
}

func (o *MwUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /api/mw/{id}][%d] mwUpdateOK  %+v", 200, o.Payload)
}

func (o *MwUpdateOK) GetPayload() *MwUpdateOKBody {
	return o.Payload
}

func (o *MwUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(MwUpdateOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMwUpdateInternalServerError creates a MwUpdateInternalServerError with default headers values
func NewMwUpdateInternalServerError() *MwUpdateInternalServerError {
	return &MwUpdateInternalServerError{}
}

/*MwUpdateInternalServerError handles this case with default header values.

Generic error specified by `Status` and `Error` fields
*/
type MwUpdateInternalServerError struct {
	Payload *models.Payload
}

func (o *MwUpdateInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /api/mw/{id}][%d] mwUpdateInternalServerError  %+v", 500, o.Payload)
}

func (o *MwUpdateInternalServerError) GetPayload() *models.Payload {
	return o.Payload
}

func (o *MwUpdateInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Payload)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*MwUpdateOKBody mw update o k body
swagger:model MwUpdateOKBody
*/
type MwUpdateOKBody struct {

	// error
	Error string `json:"Error,omitempty"`

	// payload
	Payload *MwUpdateOKBodyPayload `json:"Payload,omitempty"`

	// status
	Status string `json:"Status,omitempty"`
}

// Validate validates this mw update o k body
func (o *MwUpdateOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validatePayload(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *MwUpdateOKBody) validatePayload(formats strfmt.Registry) error {

	if swag.IsZero(o.Payload) { // not required
		return nil
	}

	if o.Payload != nil {
		if err := o.Payload.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("mwUpdateOK" + "." + "Payload")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *MwUpdateOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *MwUpdateOKBody) UnmarshalBinary(b []byte) error {
	var res MwUpdateOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*MwUpdateOKBodyPayload mw update o k body payload
swagger:model MwUpdateOKBodyPayload
*/
type MwUpdateOKBodyPayload struct {

	// bundle ID
	BundleID string `json:"BundleID,omitempty"`
}

// Validate validates this mw update o k body payload
func (o *MwUpdateOKBodyPayload) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *MwUpdateOKBodyPayload) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *MwUpdateOKBodyPayload) UnmarshalBinary(b []byte) error {
	var res MwUpdateOKBodyPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
