basePath: /
consumes:
- application/json
definitions:
  AccessDefinition:
    properties:
      allowed_urls:
        items:
          $ref: '#/definitions/AccessSpec'
        type: array
        x-go-name: AllowedUrls
      api_id:
        type: string
        x-go-name: ApiId
      api_name:
        type: string
        x-go-name: ApiName
      versions:
        items:
          type: string
        type: array
        x-go-name: Versions
    type: object
    x-go-package: github.com/TykTechnologies/mserv/coprocess/bindings/go
  AccessSpec:
    properties:
      methods:
        items:
          type: string
        type: array
        x-go-name: Methods
      url:
        type: string
        x-go-name: Url
    type: object
    x-go-package: github.com/TykTechnologies/mserv/coprocess/bindings/go
  BasicAuthData:
    properties:
      hash:
        type: string
        x-go-name: Hash
      password:
        type: string
        x-go-name: Password
    type: object
    x-go-package: github.com/TykTechnologies/mserv/coprocess/bindings/go
  BundleManifest:
    properties:
      checksum:
        type: string
        x-go-name: Checksum
      custom_middleware:
        $ref: '#/definitions/MiddlewareSection'
      file_list:
        items:
          type: string
        type: array
        x-go-name: FileList
      signature:
        type: string
        x-go-name: Signature
    type: object
    x-go-package: github.com/TykTechnologies/mserv/vendor/github.com/TykTechnologies/tyk/apidef
  File:
    properties:
      Data:
        $ref: '#/definitions/File'
      Header:
        $ref: '#/definitions/FileHeader'
    title: File represents an uploaded file.
    type: object
    x-go-package: github.com/TykTechnologies/mserv/vendor/github.com/go-openapi/runtime
  FileHeader:
    properties:
      Filename:
        type: string
      Header:
        $ref: '#/definitions/MIMEHeader'
      Size:
        format: int64
        type: integer
    title: A FileHeader describes a file part of a multipart request.
    type: object
    x-go-package: mime/multipart
  HReport:
    properties:
      GRPCStarted:
        type: boolean
      HTTPStarted:
        type: boolean
    type: object
    x-go-package: github.com/TykTechnologies/mserv/health
  HookType:
    format: int32
    type: integer
    x-go-package: github.com/TykTechnologies/mserv/coprocess/bindings/go
  IdExtractorSource:
    type: string
    x-go-package: github.com/TykTechnologies/mserv/vendor/github.com/TykTechnologies/tyk/apidef
  IdExtractorType:
    type: string
    x-go-package: github.com/TykTechnologies/mserv/vendor/github.com/TykTechnologies/tyk/apidef
  JWTData:
    properties:
      secret:
        type: string
        x-go-name: Secret
    type: object
    x-go-package: github.com/TykTechnologies/mserv/coprocess/bindings/go
  MIMEHeader:
    additionalProperties:
      items:
        type: string
      type: array
    description: |-
      A MIMEHeader represents a MIME-style header mapping
      keys to sets of values.
    type: object
    x-go-package: net/textproto
  MW:
    properties:
      APIID:
        type: string
      Active:
        type: boolean
      Added:
        format: date-time
        type: string
      BundleRef:
        type: string
      DownloadOnly:
        type: boolean
      Manifest:
        $ref: '#/definitions/BundleManifest'
      OrgID:
        type: string
      Plugins:
        items:
          $ref: '#/definitions/Plugin'
        type: array
      UID:
        type: string
    type: object
    x-go-package: github.com/TykTechnologies/mserv/storage
  MiddlewareDefinition:
    properties:
      name:
        type: string
        x-go-name: Name
      path:
        type: string
        x-go-name: Path
      raw_body_only:
        type: boolean
        x-go-name: RawBodyOnly
      require_session:
        type: boolean
        x-go-name: RequireSession
    type: object
    x-go-package: github.com/TykTechnologies/mserv/vendor/github.com/TykTechnologies/tyk/apidef
  MiddlewareDriver:
    type: string
    x-go-package: github.com/TykTechnologies/mserv/vendor/github.com/TykTechnologies/tyk/apidef
  MiddlewareIdExtractor:
    properties:
      extract_from:
        $ref: '#/definitions/IdExtractorSource'
      extract_with:
        $ref: '#/definitions/IdExtractorType'
      extractor_config:
        additionalProperties:
          type: object
        type: object
        x-go-name: ExtractorConfig
    type: object
    x-go-package: github.com/TykTechnologies/mserv/vendor/github.com/TykTechnologies/tyk/apidef
  MiddlewareSection:
    properties:
      auth_check:
        $ref: '#/definitions/MiddlewareDefinition'
      driver:
        $ref: '#/definitions/MiddlewareDriver'
      id_extractor:
        $ref: '#/definitions/MiddlewareIdExtractor'
      post:
        items:
          $ref: '#/definitions/MiddlewareDefinition'
        type: array
        x-go-name: Post
      post_key_auth:
        items:
          $ref: '#/definitions/MiddlewareDefinition'
        type: array
        x-go-name: PostKeyAuth
      pre:
        items:
          $ref: '#/definitions/MiddlewareDefinition'
        type: array
        x-go-name: Pre
      response:
        items:
          $ref: '#/definitions/MiddlewareDefinition'
        type: array
        x-go-name: Response
    type: object
    x-go-package: github.com/TykTechnologies/mserv/vendor/github.com/TykTechnologies/tyk/apidef
  MiniRequestObject:
    properties:
      add_params:
        additionalProperties:
          type: string
        type: object
        x-go-name: AddParams
      body:
        type: string
        x-go-name: Body
      delete_headers:
        items:
          type: string
        type: array
        x-go-name: DeleteHeaders
      delete_params:
        items:
          type: string
        type: array
        x-go-name: DeleteParams
      extended_params:
        additionalProperties:
          type: string
        type: object
        x-go-name: ExtendedParams
      headers:
        additionalProperties:
          type: string
        type: object
        x-go-name: Headers
      method:
        type: string
        x-go-name: Method
      params:
        additionalProperties:
          type: string
        type: object
        x-go-name: Params
      raw_body:
        items:
          format: uint8
          type: integer
        type: array
        x-go-name: RawBody
      request_uri:
        type: string
        x-go-name: RequestUri
      return_overrides:
        $ref: '#/definitions/ReturnOverrides'
      scheme:
        type: string
        x-go-name: Scheme
      set_headers:
        additionalProperties:
          type: string
        type: object
        x-go-name: SetHeaders
      url:
        type: string
        x-go-name: Url
    type: object
    x-go-package: github.com/TykTechnologies/mserv/coprocess/bindings/go
  Monitor:
    properties:
      trigger_limits:
        items:
          format: double
          type: number
        type: array
        x-go-name: TriggerLimits
    type: object
    x-go-package: github.com/TykTechnologies/mserv/coprocess/bindings/go
  Object:
    properties:
      hook_name:
        type: string
        x-go-name: HookName
      hook_type:
        $ref: '#/definitions/HookType'
      metadata:
        additionalProperties:
          type: string
        type: object
        x-go-name: Metadata
      request:
        $ref: '#/definitions/MiniRequestObject'
      session:
        $ref: '#/definitions/SessionState'
      spec:
        additionalProperties:
          type: string
        type: object
        x-go-name: Spec
    type: object
    x-go-package: github.com/TykTechnologies/mserv/coprocess/bindings/go
  Payload:
    description: Payload is the default response
    properties:
      Error:
        type: string
      Payload:
        type: object
      Status:
        type: string
    type: object
    x-go-package: github.com/TykTechnologies/mserv/models
  Plugin:
    properties:
      FileName:
        type: string
      FileRef:
        type: string
      Name:
        type: string
      Type:
        $ref: '#/definitions/HookType'
      UID:
        type: string
    type: object
    x-go-package: github.com/TykTechnologies/mserv/storage
  ReturnOverrides:
    properties:
      headers:
        additionalProperties:
          type: string
        type: object
        x-go-name: Headers
      response_code:
        format: int32
        type: integer
        x-go-name: ResponseCode
      response_error:
        type: string
        x-go-name: ResponseError
    type: object
    x-go-package: github.com/TykTechnologies/mserv/coprocess/bindings/go
  SessionState:
    properties:
      access_rights:
        additionalProperties:
          $ref: '#/definitions/AccessDefinition'
        type: object
        x-go-name: AccessRights
      alias:
        type: string
        x-go-name: Alias
      allowance:
        format: double
        type: number
        x-go-name: Allowance
      apply_policies:
        items:
          type: string
        type: array
        x-go-name: ApplyPolicies
      apply_policy_id:
        type: string
        x-go-name: ApplyPolicyId
      basic_auth_data:
        $ref: '#/definitions/BasicAuthData'
      certificate:
        type: string
        x-go-name: Certificate
      data_expires:
        format: int64
        type: integer
        x-go-name: DataExpires
      enable_detailed_recording:
        type: boolean
        x-go-name: EnableDetailedRecording
      expires:
        format: int64
        type: integer
        x-go-name: Expires
      hmac_enabled:
        type: boolean
        x-go-name: HmacEnabled
      hmac_secret:
        type: string
        x-go-name: HmacSecret
      id_extractor_deadline:
        format: int64
        type: integer
        x-go-name: IdExtractorDeadline
      is_inactive:
        type: boolean
        x-go-name: IsInactive
      jwt_data:
        $ref: '#/definitions/JWTData'
      last_check:
        format: int64
        type: integer
        x-go-name: LastCheck
      last_updated:
        type: string
        x-go-name: LastUpdated
      metadata:
        additionalProperties:
          type: string
        type: object
        x-go-name: Metadata
      monitor:
        $ref: '#/definitions/Monitor'
      oauth_client_id:
        type: string
        x-go-name: OauthClientId
      oauth_keys:
        additionalProperties:
          type: string
        type: object
        x-go-name: OauthKeys
      org_id:
        type: string
        x-go-name: OrgId
      per:
        format: double
        type: number
        x-go-name: Per
      quota_max:
        format: int64
        type: integer
        x-go-name: QuotaMax
      quota_remaining:
        format: int64
        type: integer
        x-go-name: QuotaRemaining
      quota_renewal_rate:
        format: int64
        type: integer
        x-go-name: QuotaRenewalRate
      quota_renews:
        format: int64
        type: integer
        x-go-name: QuotaRenews
      rate:
        format: double
        type: number
        x-go-name: Rate
      session_lifetime:
        format: int64
        type: integer
        x-go-name: SessionLifetime
      tags:
        items:
          type: string
        type: array
        x-go-name: Tags
    type: object
    x-go-package: github.com/TykTechnologies/mserv/coprocess/bindings/go
host: localhost:8989
info:
  description: Provides access to operations over an Mserv service.
  title: Mserv API.
  version: 0.0.1
paths:
  /api/mw:
    post:
      description: Expects a file bundle in `uploadfile` form field.
      operationId: mwAdd
      parameters:
      - in: formData
        name: uploadfile
        required: true
        type: file
        x-go-name: UploadFile
      - in: query
        name: store_only
        type: boolean
        x-go-name: StoreOnly
      - in: query
        name: api_id
        type: string
        x-go-name: APIID
      responses:
        "200":
          $ref: '#/responses/mwIDResponse'
        "500":
          $ref: '#/responses/genericErrorResponse'
      security:
      - api_key: []
      summary: Adds a new middleware. If `store_only` field is true it will only be
        available for download.
      tags:
      - mw
  /api/mw/{id}:
    delete:
      operationId: mwDelete
      parameters:
      - in: path
        name: id
        required: true
        type: string
        x-go-name: ID
      responses:
        "200":
          $ref: '#/responses/mwIDResponse'
        "500":
          $ref: '#/responses/genericErrorResponse'
      security:
      - api_key: []
      summary: Deletes a middleware specified by {id}.
      tags:
      - mw
    get:
      operationId: mwFetch
      parameters:
      - in: path
        name: id
        required: true
        type: string
        x-go-name: ID
      responses:
        "200":
          $ref: '#/responses/mwResponse'
        "500":
          $ref: '#/responses/genericErrorResponse'
      security:
      - api_key: []
      summary: Fetches a middleware specified by {id}.
      tags:
      - mw
    put:
      description: Expects a file bundle in `uploadfile` form field.
      operationId: mwUpdate
      parameters:
      - in: path
        name: id
        required: true
        type: string
        x-go-name: ID
      - in: formData
        name: uploadfile
        required: true
        type: file
        x-go-name: UploadFile
      responses:
        "200":
          $ref: '#/responses/mwIDResponse'
        "500":
          $ref: '#/responses/genericErrorResponse'
      security:
      - api_key: []
      summary: Updates a middleware specified by {id}.
      tags:
      - mw
  /api/mw/bundle/{id}:
    get:
      operationId: mwFetchBundle
      parameters:
      - in: path
        name: id
        required: true
        type: string
        x-go-name: ID
      produces:
      - application/octet-stream
      responses:
        "200":
          $ref: '#/responses/mwBundleResponse'
        "500":
          $ref: '#/responses/genericErrorResponse'
      security:
      - api_key: []
      summary: Fetches a middleware bundle file specified by {id}.
      tags:
      - mw
  /api/mw/master/all:
    get:
      operationId: mwListAll
      responses:
        "200":
          $ref: '#/responses/mwListResponse'
        "500":
          $ref: '#/responses/genericErrorResponse'
      security:
      - api_key: []
      summary: Lists all middleware.
      tags:
      - mw
  /execute/{name}:
    post:
      description: Expects a coprocess.Object encoded as JSON in the request body
        and returns the result in the same way.
      operationId: invoke
      parameters:
      - in: path
        name: name
        required: true
        type: string
        x-go-name: Name
      - in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/Object'
      responses:
        "200":
          $ref: '#/responses/invocationResponse'
        "500":
          $ref: '#/responses/genericErrorResponse'
      security:
      - api_key: []
      summary: Invokes a middleware by {name}.
      tags:
      - invocation
  /health:
    get:
      operationId: health
      responses:
        "200":
          $ref: '#/responses/healthResponse'
        "500":
          $ref: '#/responses/healthResponse'
      summary: Query health status of Mserv service.
      tags:
      - system
produces:
- application/json
responses:
  genericErrorResponse:
    description: Generic error specified by `Status` and `Error` fields
    schema:
      $ref: '#/definitions/Payload'
  healthResponse:
    description: Health status response
    schema:
      properties:
        Error:
          type: string
        Payload:
          $ref: '#/definitions/HReport'
        Status:
          type: string
      type: object
  invocationResponse:
    description: Middleware invocation response
    schema:
      properties:
        Error:
          type: string
        Payload:
          $ref: '#/definitions/Object'
        Status:
          type: string
      type: object
  mwBundleResponse:
    description: Middleware bundle as a file
    schema:
      $ref: '#/definitions/File'
  mwIDResponse:
    description: Response that only includes the ID of the middleware as `BundleID`
      in the `Payload`
    schema:
      properties:
        Error:
          type: string
        Payload:
          properties:
            BundleID:
              type: string
          type: object
        Status:
          type: string
      type: object
  mwListResponse:
    description: List of full middleware representations in the `Payload`
    schema:
      properties:
        Error:
          type: string
        Payload:
          items:
            $ref: '#/definitions/MW'
          type: array
        Status:
          type: string
      type: object
  mwResponse:
    description: Full middleware response in the `Payload`
    schema:
      properties:
        Error:
          type: string
        Payload:
          $ref: '#/definitions/MW'
        Status:
          type: string
      type: object
schemes:
- http
- https
securityDefinitions:
  api_key:
    in: header
    name: X-Api-Key
    type: apiKey
swagger: "2.0"
