// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AccessDefinition AccessDefinition defines which versions of an API a key has access to
//
// swagger:model AccessDefinition
type AccessDefinition struct {

	// API ID
	APIID string `json:"api_id,omitempty"`

	// API name
	APIName string `json:"api_name,omitempty"`

	// allowance scope
	AllowanceScope string `json:"allowance_scope,omitempty"`

	// allowed u r ls
	AllowedURLs []*AccessSpec `json:"allowed_urls"`

	// versions
	Versions []string `json:"versions"`

	// limit
	Limit *APILimit `json:"limit,omitempty"`
}

// Validate validates this access definition
func (m *AccessDefinition) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAllowedURLs(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLimit(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AccessDefinition) validateAllowedURLs(formats strfmt.Registry) error {
	if swag.IsZero(m.AllowedURLs) { // not required
		return nil
	}

	for i := 0; i < len(m.AllowedURLs); i++ {
		if swag.IsZero(m.AllowedURLs[i]) { // not required
			continue
		}

		if m.AllowedURLs[i] != nil {
			if err := m.AllowedURLs[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("allowed_urls" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("allowed_urls" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *AccessDefinition) validateLimit(formats strfmt.Registry) error {
	if swag.IsZero(m.Limit) { // not required
		return nil
	}

	if m.Limit != nil {
		if err := m.Limit.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("limit")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("limit")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this access definition based on the context it is used
func (m *AccessDefinition) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAllowedURLs(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateLimit(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AccessDefinition) contextValidateAllowedURLs(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.AllowedURLs); i++ {

		if m.AllowedURLs[i] != nil {

			if swag.IsZero(m.AllowedURLs[i]) { // not required
				return nil
			}

			if err := m.AllowedURLs[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("allowed_urls" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("allowed_urls" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *AccessDefinition) contextValidateLimit(ctx context.Context, formats strfmt.Registry) error {

	if m.Limit != nil {

		if swag.IsZero(m.Limit) { // not required
			return nil
		}

		if err := m.Limit.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("limit")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("limit")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AccessDefinition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccessDefinition) UnmarshalBinary(b []byte) error {
	var res AccessDefinition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
