// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AccessDefinition access definition
//
// swagger:model AccessDefinition
type AccessDefinition struct {

	// allowed urls
	AllowedUrls []*AccessSpec `json:"allowed_urls"`

	// Api Id
	APIID string `json:"api_id,omitempty"`

	// Api name
	APIName string `json:"api_name,omitempty"`

	// versions
	Versions []string `json:"versions"`
}

// Validate validates this access definition
func (m *AccessDefinition) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAllowedUrls(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AccessDefinition) validateAllowedUrls(formats strfmt.Registry) error {

	if swag.IsZero(m.AllowedUrls) { // not required
		return nil
	}

	for i := 0; i < len(m.AllowedUrls); i++ {
		if swag.IsZero(m.AllowedUrls[i]) { // not required
			continue
		}

		if m.AllowedUrls[i] != nil {
			if err := m.AllowedUrls[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("allowed_urls" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *AccessDefinition) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccessDefinition) UnmarshalBinary(b []byte) error {
	var res AccessDefinition
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
