// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// AuthProviderCode auth provider code
//
// swagger:model AuthProviderCode
type AuthProviderCode string

// Validate validates this auth provider code
func (m AuthProviderCode) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this auth provider code based on context it is used
func (m AuthProviderCode) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
