// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// AuthTypeEnum auth type enum
//
// swagger:model AuthTypeEnum
type AuthTypeEnum string

// Validate validates this auth type enum
func (m AuthTypeEnum) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this auth type enum based on context it is used
func (m AuthTypeEnum) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
