// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// AuthorizeRequestType AuthorizeRequestType is the type for OAuth param `response_type`
//
// swagger:model AuthorizeRequestType
type AuthorizeRequestType string

// Validate validates this authorize request type
func (m AuthorizeRequestType) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this authorize request type based on context it is used
func (m AuthorizeRequestType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
