// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BasicAuthData basic auth data
//
// swagger:model BasicAuthData
type BasicAuthData struct {

	// hash
	Hash string `json:"hash,omitempty"`

	// password
	Password string `json:"password,omitempty"`
}

// Validate validates this basic auth data
func (m *BasicAuthData) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BasicAuthData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BasicAuthData) UnmarshalBinary(b []byte) error {
	var res BasicAuthData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
