// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CircuitBreakerMeta circuit breaker meta
//
// swagger:model CircuitBreakerMeta
type CircuitBreakerMeta struct {

	// method
	Method string `json:"method,omitempty"`

	// path
	Path string `json:"path,omitempty"`

	// return to service after
	ReturnToServiceAfter int64 `json:"return_to_service_after,omitempty"`

	// samples
	Samples int64 `json:"samples,omitempty"`

	// threshold percent
	ThresholdPercent float64 `json:"threshold_percent,omitempty"`
}

// Validate validates this circuit breaker meta
func (m *CircuitBreakerMeta) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this circuit breaker meta based on context it is used
func (m *CircuitBreakerMeta) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CircuitBreakerMeta) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CircuitBreakerMeta) UnmarshalBinary(b []byte) error {
	var res CircuitBreakerMeta
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
