// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// EndPointMeta end point meta
//
// swagger:model EndPointMeta
type EndPointMeta struct {

	// ignore case
	IgnoreCase bool `json:"ignore_case,omitempty"`

	// method actions
	MethodActions map[string]EndpointMethodMeta `json:"method_actions,omitempty"`

	// path
	Path string `json:"path,omitempty"`
}

// Validate validates this end point meta
func (m *EndPointMeta) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMethodActions(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EndPointMeta) validateMethodActions(formats strfmt.Registry) error {
	if swag.IsZero(m.MethodActions) { // not required
		return nil
	}

	for k := range m.MethodActions {

		if err := validate.Required("method_actions"+"."+k, "body", m.MethodActions[k]); err != nil {
			return err
		}
		if val, ok := m.MethodActions[k]; ok {
			if err := val.Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("method_actions" + "." + k)
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("method_actions" + "." + k)
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this end point meta based on the context it is used
func (m *EndPointMeta) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMethodActions(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EndPointMeta) contextValidateMethodActions(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.MethodActions {

		if val, ok := m.MethodActions[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *EndPointMeta) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EndPointMeta) UnmarshalBinary(b []byte) error {
	var res EndPointMeta
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
