// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// EndpointMethodAction endpoint method action
//
// swagger:model EndpointMethodAction
type EndpointMethodAction string

// Validate validates this endpoint method action
func (m EndpointMethodAction) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this endpoint method action based on context it is used
func (m EndpointMethodAction) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
