// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// EventHandlerMetaConfig event handler meta config
//
// swagger:model EventHandlerMetaConfig
type EventHandlerMetaConfig struct {

	// events
	Events map[string][]EventHandlerTriggerConfig `json:"events,omitempty"`
}

// Validate validates this event handler meta config
func (m *EventHandlerMetaConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEvents(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EventHandlerMetaConfig) validateEvents(formats strfmt.Registry) error {
	if swag.IsZero(m.Events) { // not required
		return nil
	}

	for k := range m.Events {

		if err := validate.Required("events"+"."+k, "body", m.Events[k]); err != nil {
			return err
		}

		for i := 0; i < len(m.Events[k]); i++ {

			if err := m.Events[k][i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("events" + "." + k + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("events" + "." + k + "." + strconv.Itoa(i))
				}
				return err
			}

		}

	}

	return nil
}

// ContextValidate validate this event handler meta config based on the context it is used
func (m *EventHandlerMetaConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateEvents(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *EventHandlerMetaConfig) contextValidateEvents(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.Events {

		for i := 0; i < len(m.Events[k]); i++ {

			if swag.IsZero(m.Events[k][i]) { // not required
				return nil
			}

			if err := m.Events[k][i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("events" + "." + k + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("events" + "." + k + "." + strconv.Itoa(i))
				}
				return err
			}

		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *EventHandlerMetaConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EventHandlerMetaConfig) UnmarshalBinary(b []byte) error {
	var res EventHandlerMetaConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
