// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// FileHeader A FileHeader describes a file part of a multipart request.
//
// swagger:model FileHeader
type FileHeader struct {

	// filename
	Filename string `json:"Filename,omitempty"`

	// header
	Header MIMEHeader `json:"Header,omitempty"`

	// size
	Size int64 `json:"Size,omitempty"`
}

// Validate validates this file header
func (m *FileHeader) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHeader(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FileHeader) validateHeader(formats strfmt.Registry) error {

	if swag.IsZero(m.Header) { // not required
		return nil
	}

	if err := m.Header.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("Header")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *FileHeader) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FileHeader) UnmarshalBinary(b []byte) error {
	var res FileHeader
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
