// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GlobalRateLimit global rate limit
//
// swagger:model GlobalRateLimit
type GlobalRateLimit struct {

	// per
	Per float64 `json:"per,omitempty"`

	// rate
	Rate float64 `json:"rate,omitempty"`
}

// Validate validates this global rate limit
func (m *GlobalRateLimit) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this global rate limit based on context it is used
func (m *GlobalRateLimit) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GlobalRateLimit) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GlobalRateLimit) UnmarshalBinary(b []byte) error {
	var res GlobalRateLimit
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
