// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HReport h report
//
// swagger:model HReport
type HReport struct {

	// g RPC started
	GRPCStarted bool `json:"GRPCStarted,omitempty"`

	// HTTP started
	HTTPStarted bool `json:"HTTPStarted,omitempty"`
}

// Validate validates this h report
func (m *HReport) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HReport) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HReport) UnmarshalBinary(b []byte) error {
	var res HReport
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
