// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// HashType hash type
//
// swagger:model HashType
type HashType string

// Validate validates this hash type
func (m HashType) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this hash type based on context it is used
func (m HashType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
