// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// HeaderInjectionMeta header injection meta
//
// swagger:model HeaderInjectionMeta
type HeaderInjectionMeta struct {

	// act on response
	ActOnResponse bool `json:"act_on,omitempty"`

	// add headers
	AddHeaders map[string]string `json:"add_headers,omitempty"`

	// delete headers
	DeleteHeaders []string `json:"delete_headers"`

	// method
	Method string `json:"method,omitempty"`

	// path
	Path string `json:"path,omitempty"`
}

// Validate validates this header injection meta
func (m *HeaderInjectionMeta) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this header injection meta based on context it is used
func (m *HeaderInjectionMeta) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HeaderInjectionMeta) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HeaderInjectionMeta) UnmarshalBinary(b []byte) error {
	var res HeaderInjectionMeta
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
