// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// HookType hook type
//
// swagger:model HookType
type HookType int32

// Validate validates this hook type
func (m HookType) Validate(formats strfmt.Registry) error {
	return nil
}
