// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// IDExtractorType Id extractor type
//
// swagger:model IdExtractorType
type IDExtractorType string

// Validate validates this Id extractor type
func (m IDExtractorType) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this Id extractor type based on context it is used
func (m IDExtractorType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
