// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// IDExtractorSource Id extractor source
//
// swagger:model IdExtractorSource
type IDExtractorSource string

// Validate validates this Id extractor source
func (m IDExtractorSource) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this Id extractor source based on context it is used
func (m IDExtractorSource) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
