// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MethodTransformMeta method transform meta
//
// swagger:model MethodTransformMeta
type MethodTransformMeta struct {

	// method
	Method string `json:"method,omitempty"`

	// path
	Path string `json:"path,omitempty"`

	// to method
	ToMethod string `json:"to_method,omitempty"`
}

// Validate validates this method transform meta
func (m *MethodTransformMeta) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this method transform meta based on context it is used
func (m *MethodTransformMeta) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MethodTransformMeta) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MethodTransformMeta) UnmarshalBinary(b []byte) error {
	var res MethodTransformMeta
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
