// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
)

// MiddlewareDriver middleware driver
//
// swagger:model MiddlewareDriver
type MiddlewareDriver string

// Validate validates this middleware driver
func (m MiddlewareDriver) Validate(formats strfmt.Registry) error {
	return nil
}
