// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OIDProviderConfig o ID provider config
//
// swagger:model OIDProviderConfig
type OIDProviderConfig struct {

	// client i ds
	ClientIDs map[string]string `json:"client_ids,omitempty"`

	// issuer
	Issuer string `json:"issuer,omitempty"`
}

// Validate validates this o ID provider config
func (m *OIDProviderConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this o ID provider config based on context it is used
func (m *OIDProviderConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OIDProviderConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OIDProviderConfig) UnmarshalBinary(b []byte) error {
	var res OIDProviderConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
