// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Payload Payload is the default response
//
// swagger:model Payload
type Payload struct {

	// error
	Error string `json:"Error,omitempty"`

	// payload
	Payload interface{} `json:"Payload,omitempty"`

	// status
	Status string `json:"Status,omitempty"`
}

// Validate validates this payload
func (m *Payload) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this payload based on context it is used
func (m *Payload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Payload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Payload) UnmarshalBinary(b []byte) error {
	var res Payload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
