// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RequestSigningMeta request signing meta
//
// swagger:model RequestSigningMeta
type RequestSigningMeta struct {

	// algorithm
	Algorithm string `json:"algorithm,omitempty"`

	// certificate Id
	CertificateID string `json:"certificate_id,omitempty"`

	// header list
	HeaderList []string `json:"header_list"`

	// is enabled
	IsEnabled bool `json:"is_enabled,omitempty"`

	// key Id
	KeyID string `json:"key_id,omitempty"`

	// secret
	Secret string `json:"secret,omitempty"`

	// signature header
	SignatureHeader string `json:"signature_header,omitempty"`
}

// Validate validates this request signing meta
func (m *RequestSigningMeta) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this request signing meta based on context it is used
func (m *RequestSigningMeta) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RequestSigningMeta) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RequestSigningMeta) UnmarshalBinary(b []byte) error {
	var res RequestSigningMeta
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
