// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// RequestInputType request input type
//
// swagger:model RequestInputType
type RequestInputType string

// Validate validates this request input type
func (m RequestInputType) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this request input type based on context it is used
func (m RequestInputType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
