// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// RoutingTriggerOnType routing trigger on type
//
// swagger:model RoutingTriggerOnType
type RoutingTriggerOnType string

// Validate validates this routing trigger on type
func (m RoutingTriggerOnType) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this routing trigger on type based on context it is used
func (m RoutingTriggerOnType) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
