// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ServiceDiscoveryConfiguration service discovery configuration
//
// swagger:model ServiceDiscoveryConfiguration
type ServiceDiscoveryConfiguration struct {

	// cache timeout
	CacheTimeout int64 `json:"cache_timeout,omitempty"`

	// data path
	DataPath string `json:"data_path,omitempty"`

	// endpoint returns list
	EndpointReturnsList bool `json:"endpoint_returns_list,omitempty"`

	// parent data path
	ParentDataPath string `json:"parent_data_path,omitempty"`

	// port data path
	PortDataPath string `json:"port_data_path,omitempty"`

	// query endpoint
	QueryEndpoint string `json:"query_endpoint,omitempty"`

	// target path
	TargetPath string `json:"target_path,omitempty"`

	// use discovery service
	UseDiscoveryService bool `json:"use_discovery_service,omitempty"`

	// use nested query
	UseNestedQuery bool `json:"use_nested_query,omitempty"`

	// use target list
	UseTargetList bool `json:"use_target_list,omitempty"`
}

// Validate validates this service discovery configuration
func (m *ServiceDiscoveryConfiguration) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this service discovery configuration based on context it is used
func (m *ServiceDiscoveryConfiguration) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ServiceDiscoveryConfiguration) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ServiceDiscoveryConfiguration) UnmarshalBinary(b []byte) error {
	var res ServiceDiscoveryConfiguration
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
