// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// SessionProviderCode session provider code
//
// swagger:model SessionProviderCode
type SessionProviderCode string

// Validate validates this session provider code
func (m SessionProviderCode) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this session provider code based on context it is used
func (m SessionProviderCode) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
