// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SignatureConfig signature config
//
// swagger:model SignatureConfig
type SignatureConfig struct {

	// algorithm
	Algorithm string `json:"algorithm,omitempty"`

	// allowed clock skew
	AllowedClockSkew int64 `json:"allowed_clock_skew,omitempty"`

	// error code
	ErrorCode int64 `json:"error_code,omitempty"`

	// error message
	ErrorMessage string `json:"error_message,omitempty"`

	// header
	Header string `json:"header,omitempty"`

	// secret
	Secret string `json:"secret,omitempty"`
}

// Validate validates this signature config
func (m *SignatureConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this signature config based on context it is used
func (m *SignatureConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SignatureConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SignatureConfig) UnmarshalBinary(b []byte) error {
	var res SignatureConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
