// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// StorageEngineCode storage engine code
//
// swagger:model StorageEngineCode
type StorageEngineCode string

// Validate validates this storage engine code
func (m StorageEngineCode) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this storage engine code based on context it is used
func (m StorageEngineCode) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
