// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// StringRegexMap string regex map
//
// swagger:model StringRegexMap
type StringRegexMap struct {

	// match pattern
	MatchPattern string `json:"match_rx,omitempty"`

	// reverse
	Reverse bool `json:"reverse,omitempty"`
}

// Validate validates this string regex map
func (m *StringRegexMap) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this string regex map based on context it is used
func (m *StringRegexMap) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StringRegexMap) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StringRegexMap) UnmarshalBinary(b []byte) error {
	var res StringRegexMap
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
