// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// TemplateMode template mode
//
// swagger:model TemplateMode
type TemplateMode string

// Validate validates this template mode
func (m TemplateMode) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this template mode based on context it is used
func (m TemplateMode) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
