// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TemplateData template data
//
// swagger:model TemplateData
type TemplateData struct {

	// enable session
	EnableSession bool `json:"enable_session,omitempty"`

	// template source
	TemplateSource string `json:"template_source,omitempty"`

	// input type
	InputType RequestInputType `json:"input_type,omitempty"`

	// template mode
	TemplateMode TemplateMode `json:"template_mode,omitempty"`
}

// Validate validates this template data
func (m *TemplateData) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInputType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTemplateMode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TemplateData) validateInputType(formats strfmt.Registry) error {
	if swag.IsZero(m.InputType) { // not required
		return nil
	}

	if err := m.InputType.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("input_type")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("input_type")
		}
		return err
	}

	return nil
}

func (m *TemplateData) validateTemplateMode(formats strfmt.Registry) error {
	if swag.IsZero(m.TemplateMode) { // not required
		return nil
	}

	if err := m.TemplateMode.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("template_mode")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("template_mode")
		}
		return err
	}

	return nil
}

// ContextValidate validate this template data based on the context it is used
func (m *TemplateData) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateInputType(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTemplateMode(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TemplateData) contextValidateInputType(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.InputType) { // not required
		return nil
	}

	if err := m.InputType.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("input_type")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("input_type")
		}
		return err
	}

	return nil
}

func (m *TemplateData) contextValidateTemplateMode(ctx context.Context, formats strfmt.Registry) error {

	if swag.IsZero(m.TemplateMode) { // not required
		return nil
	}

	if err := m.TemplateMode.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("template_mode")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("template_mode")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TemplateData) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TemplateData) UnmarshalBinary(b []byte) error {
	var res TemplateData
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
