// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TemplateMeta template meta
//
// swagger:model TemplateMeta
type TemplateMeta struct {

	// method
	Method string `json:"method,omitempty"`

	// path
	Path string `json:"path,omitempty"`

	// template data
	TemplateData *TemplateData `json:"template_data,omitempty"`
}

// Validate validates this template meta
func (m *TemplateMeta) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTemplateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TemplateMeta) validateTemplateData(formats strfmt.Registry) error {
	if swag.IsZero(m.TemplateData) { // not required
		return nil
	}

	if m.TemplateData != nil {
		if err := m.TemplateData.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("template_data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("template_data")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this template meta based on the context it is used
func (m *TemplateMeta) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateTemplateData(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TemplateMeta) contextValidateTemplateData(ctx context.Context, formats strfmt.Registry) error {

	if m.TemplateData != nil {

		if swag.IsZero(m.TemplateData) { // not required
			return nil
		}

		if err := m.TemplateData.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("template_data")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("template_data")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TemplateMeta) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TemplateMeta) UnmarshalBinary(b []byte) error {
	var res TemplateMeta
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
