// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TrackEndpointMeta track endpoint meta
//
// swagger:model TrackEndpointMeta
type TrackEndpointMeta struct {

	// method
	Method string `json:"method,omitempty"`

	// path
	Path string `json:"path,omitempty"`
}

// Validate validates this track endpoint meta
func (m *TrackEndpointMeta) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this track endpoint meta based on context it is used
func (m *TrackEndpointMeta) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TrackEndpointMeta) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TrackEndpointMeta) UnmarshalBinary(b []byte) error {
	var res TrackEndpointMeta
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
