// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TransformJQMeta transform j q meta
//
// swagger:model TransformJQMeta
type TransformJQMeta struct {

	// filter
	Filter string `json:"filter,omitempty"`

	// method
	Method string `json:"method,omitempty"`

	// path
	Path string `json:"path,omitempty"`
}

// Validate validates this transform j q meta
func (m *TransformJQMeta) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this transform j q meta based on context it is used
func (m *TransformJQMeta) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TransformJQMeta) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TransformJQMeta) UnmarshalBinary(b []byte) error {
	var res TransformJQMeta
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
