// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// TykEventHandlerName tyk event handler name
//
// swagger:model TykEventHandlerName
type TykEventHandlerName string

// Validate validates this tyk event handler name
func (m TykEventHandlerName) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this tyk event handler name based on context it is used
func (m TykEventHandlerName) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
