// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VirtualMeta virtual meta
//
// swagger:model VirtualMeta
type VirtualMeta struct {

	// function source type
	FunctionSourceType string `json:"function_source_type,omitempty"`

	// function source URI
	FunctionSourceURI string `json:"function_source_uri,omitempty"`

	// method
	Method string `json:"method,omitempty"`

	// path
	Path string `json:"path,omitempty"`

	// proxy on error
	ProxyOnError bool `json:"proxy_on_error,omitempty"`

	// response function name
	ResponseFunctionName string `json:"response_function_name,omitempty"`

	// use session
	UseSession bool `json:"use_session,omitempty"`
}

// Validate validates this virtual meta
func (m *VirtualMeta) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this virtual meta based on context it is used
func (m *VirtualMeta) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VirtualMeta) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VirtualMeta) UnmarshalBinary(b []byte) error {
	var res VirtualMeta
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
