name: Build and push docker image

on:
  push:
    tags:
      - "v*"

jobs:
  check-base-branch:
    runs-on: ubuntu-latest
    outputs:
      on_main: ${{ steps.contains_tag.outputs.retval }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: rickstaa/action-contains-tag@v1
        id: contains_tag
        with:
          reference: "master"
          tag: "${{ github.ref }}"

  build-and-push:
    runs-on: ubuntu-latest
    needs: check-base-branch
    steps:
      - name: Git checkout
        uses: actions/checkout@v4

      - uses: TykTechnologies/actions/docker-login@main
        with:
          dockerhub_username: ${{ secrets.DOCKER_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKER_PASSWORD }}

      - uses: TykTechnologies/actions/docker-build-push@main
        with:
          dockerfile: Dockerfile
          tags: ${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64
          repository_name: mserv
