# Create a draft release and attach mservctl binaries

name: Draft release

on:
  push:
    tags:
      - "v*"

env:
  BINARY_NAME: mservctl

jobs:
  build:
    name: Build the 'mservctl' CLI binary

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        arch: [amd64]

    runs-on: ${{ matrix.platform }}

    steps:
      - name: checkout ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build the CLI binary
        run: |
          cd mservctl
          go build -o ../bin/mservctl
          cd ..

      - name: Upload ${{ runner.os }} ${{ matrix.arch }} binary
        uses: actions/upload-artifact@v3
        with:
          name: mservctl.${{ runner.os }}.${{ matrix.arch }}
          path: bin/mservctl

  release:
    needs: [build]

    name: Create a draft release, and attach the built binaries

    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-release@v1
        id: draft-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true

      - uses: actions/download-artifact@v3
        with:
          name: mservctl.Linux.amd64
          path: mservctl.Linux.amd64

      - name: Attach Linux binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.draft-release.outputs.upload_url }}
          asset_name: mservctl.Linux.amd64
          asset_path: mservctl.Linux.amd64/mservctl
          asset_content_type: application/octet-stream

      - uses: actions/download-artifact@v3
        with:
          name: mservctl.macOS.amd64
          path: mservctl.macOS.amd64

      - name: Attach macOS binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.draft-release.outputs.upload_url }}
          asset_name: mservctl.macOS.amd64
          asset_path: mservctl.macOS.amd64/mservctl
          asset_content_type: application/octet-stream
