# Create a draft release and attach mservctl binaries

name: Draft release

on:
  push:
    branches:
      - wftest/*

jobs:
  linux:
    name: amd64 build
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout ${{ github.repository }}
        uses: actions/checkout@v2

      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'

      - name: Build
        run: |
          cd mservctl && go build -mod=vendor

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: mservctl.linux.amd64
          path: mservctl/mservctl

  macOS:
    name: macos build
    runs-on: macos-latest
    
    steps:
      - name: checkout ${{ github.repository }}
        uses: actions/checkout@v2

      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'

      - name: Build
        run: |
          cd mservctl && go build -mod=vendor

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: mservctl.macos
          path: mservctl/mservctl
  
  release:
    name: release
    runs-on: ubuntu-latest
    needs: [ linux, macOS ]

    steps:
      - uses: actions/create-release@v1
        id: draft-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true

      - uses: actions/download-artifact@v1
        with:
          name: mservctl.linux.amd64
          
      - name: upload linux binary
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.draft-release.outputs.upload_url }}
          asset_path: ./mservctl
          asset_name: mservctl.linux.amd64
          asset_content_type: application/octet-stream

      - uses: actions/download-artifact@v1
        with:
          name: mservctl.macos.amd64
          
      - name: upload macos binary
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.draft-release.outputs.upload_url }}
          asset_path: ./mservctl/mservctl
          asset_name: mservctl.macos
          asset_content_type: application/octet-stream

