name: Test, Lint, Build

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.22"

    - name: Test
      run: make test

    - name: Build server and client
      run: make build

    - name: Start Docker Compose with MongoDB and Tyk Mserv
      run: make start

    - name: Build and bundle plugins
      run: |
        make plugins
        make bundles

    - name: Install Venom command line tool
      run: go install github.com/ovh/venom/cmd/venom@latest

    - name: Run Venom tests
      run: make integration
